name: Tests

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
  push:
    branches:
      - main

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm install
    
    - name: Run unit tests
      run: npm run build-and-test

  # e2e-tests:
  #   runs-on: ubuntu-latest
    
  #   steps:
  #   - uses: actions/checkout@v4
    
  #   - name: Setup Node.js
  #     uses: actions/setup-node@v4
  #     with:
  #       node-version: '20'
  #       cache: 'npm'
    
  #   - name: Install dependencies
  #     run: npm install
    
  #   - name: Install Playwright browsers
  #     run: npx playwright install --with-deps
    
  #   - name: Build project
  #     run: npm run build
    
  #   - name: Run E2E tests
  #     run: npm run test:e2e
    
  #   - name: Upload Playwright report
  #     uses: actions/upload-artifact@v3
  #     if: failure()
  #     with:
  #       name: playwright-report
  #       path: playwright-report/
  #       retention-days: 30

  # visual-regression:
  #   runs-on: ubuntu-latest
    
  #   steps:
  #   - uses: actions/checkout@v4
    
  #   - name: Setup Node.js
  #     uses: actions/setup-node@v4
  #     with:
  #       node-version: '20'
  #       cache: 'npm'
    
  #   - name: Install dependencies
  #     run: npm ci
    
  #   - name: Install Playwright browsers
  #     run: npx playwright install --with-deps
    
  #   - name: Build project
  #     run: npm run build
    
  #   - name: Run visual regression tests
  #     run: npx playwright test tests/e2e/visual-regression.spec.js
    
  #   - name: Upload screenshots
  #     uses: actions/upload-artifact@v3
  #     if: failure()
  #     with:
  #       name: visual-regression-diffs
  #       path: test-results/
  #       retention-days: 30